/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaterDamageRouteImport } from './routes/water-damage'
import { Route as RoofingRouteImport } from './routes/roofing'
import { Route as PlumbingRouteImport } from './routes/plumbing'
import { Route as PestControlRouteImport } from './routes/pest-control'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FloorCoatingRouteImport } from './routes/floor-coating'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminFaqsRouteImport } from './routes/admin.faqs'
import { Route as AdminAbTestsRouteImport } from './routes/admin.ab-tests'

const WaterDamageRoute = WaterDamageRouteImport.update({
  id: '/water-damage',
  path: '/water-damage',
  getParentRoute: () => rootRouteImport,
} as any)
const RoofingRoute = RoofingRouteImport.update({
  id: '/roofing',
  path: '/roofing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlumbingRoute = PlumbingRouteImport.update({
  id: '/plumbing',
  path: '/plumbing',
  getParentRoute: () => rootRouteImport,
} as any)
const PestControlRoute = PestControlRouteImport.update({
  id: '/pest-control',
  path: '/pest-control',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FloorCoatingRoute = FloorCoatingRouteImport.update({
  id: '/floor-coating',
  path: '/floor-coating',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAbTestsRoute = AdminAbTestsRouteImport.update({
  id: '/ab-tests',
  path: '/ab-tests',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/floor-coating': typeof FloorCoatingRoute
  '/login': typeof LoginRoute
  '/pest-control': typeof PestControlRoute
  '/plumbing': typeof PlumbingRoute
  '/roofing': typeof RoofingRoute
  '/water-damage': typeof WaterDamageRoute
  '/admin/ab-tests': typeof AdminAbTestsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/floor-coating': typeof FloorCoatingRoute
  '/login': typeof LoginRoute
  '/pest-control': typeof PestControlRoute
  '/plumbing': typeof PlumbingRoute
  '/roofing': typeof RoofingRoute
  '/water-damage': typeof WaterDamageRoute
  '/admin/ab-tests': typeof AdminAbTestsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/floor-coating': typeof FloorCoatingRoute
  '/login': typeof LoginRoute
  '/pest-control': typeof PestControlRoute
  '/plumbing': typeof PlumbingRoute
  '/roofing': typeof RoofingRoute
  '/water-damage': typeof WaterDamageRoute
  '/admin/ab-tests': typeof AdminAbTestsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/floor-coating'
    | '/login'
    | '/pest-control'
    | '/plumbing'
    | '/roofing'
    | '/water-damage'
    | '/admin/ab-tests'
    | '/admin/faqs'
    | '/admin/leads'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/testimonials'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/floor-coating'
    | '/login'
    | '/pest-control'
    | '/plumbing'
    | '/roofing'
    | '/water-damage'
    | '/admin/ab-tests'
    | '/admin/faqs'
    | '/admin/leads'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/testimonials'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/floor-coating'
    | '/login'
    | '/pest-control'
    | '/plumbing'
    | '/roofing'
    | '/water-damage'
    | '/admin/ab-tests'
    | '/admin/faqs'
    | '/admin/leads'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/testimonials'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  FloorCoatingRoute: typeof FloorCoatingRoute
  LoginRoute: typeof LoginRoute
  PestControlRoute: typeof PestControlRoute
  PlumbingRoute: typeof PlumbingRoute
  RoofingRoute: typeof RoofingRoute
  WaterDamageRoute: typeof WaterDamageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/water-damage': {
      id: '/water-damage'
      path: '/water-damage'
      fullPath: '/water-damage'
      preLoaderRoute: typeof WaterDamageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roofing': {
      id: '/roofing'
      path: '/roofing'
      fullPath: '/roofing'
      preLoaderRoute: typeof RoofingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plumbing': {
      id: '/plumbing'
      path: '/plumbing'
      fullPath: '/plumbing'
      preLoaderRoute: typeof PlumbingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pest-control': {
      id: '/pest-control'
      path: '/pest-control'
      fullPath: '/pest-control'
      preLoaderRoute: typeof PestControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floor-coating': {
      id: '/floor-coating'
      path: '/floor-coating'
      fullPath: '/floor-coating'
      preLoaderRoute: typeof FloorCoatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ab-tests': {
      id: '/admin/ab-tests'
      path: '/ab-tests'
      fullPath: '/admin/ab-tests'
      preLoaderRoute: typeof AdminAbTestsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAbTestsRoute: typeof AdminAbTestsRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAbTestsRoute: AdminAbTestsRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  FloorCoatingRoute: FloorCoatingRoute,
  LoginRoute: LoginRoute,
  PestControlRoute: PestControlRoute,
  PlumbingRoute: PlumbingRoute,
  RoofingRoute: RoofingRoute,
  WaterDamageRoute: WaterDamageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
