/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaterDamageRouteImport } from './routes/water-damage'
import { Route as RoofingRouteImport } from './routes/roofing'
import { Route as PlumbingRouteImport } from './routes/plumbing'
import { Route as PestControlRouteImport } from './routes/pest-control'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FloorCoatingRouteImport } from './routes/floor-coating'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const WaterDamageRoute = WaterDamageRouteImport.update({
  id: '/water-damage',
  path: '/water-damage',
  getParentRoute: () => rootRouteImport,
} as any)
const RoofingRoute = RoofingRouteImport.update({
  id: '/roofing',
  path: '/roofing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlumbingRoute = PlumbingRouteImport.update({
  id: '/plumbing',
  path: '/plumbing',
  getParentRoute: () => rootRouteImport,
} as any)
const PestControlRoute = PestControlRouteImport.update({
  id: '/pest-control',
  path: '/pest-control',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FloorCoatingRoute = FloorCoatingRouteImport.update({
  id: '/floor-coating',
  path: '/floor-coating',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/floor-coating': typeof FloorCoatingRoute
  '/login': typeof LoginRoute
  '/pest-control': typeof PestControlRoute
  '/plumbing': typeof PlumbingRoute
  '/roofing': typeof RoofingRoute
  '/water-damage': typeof WaterDamageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/floor-coating': typeof FloorCoatingRoute
  '/login': typeof LoginRoute
  '/pest-control': typeof PestControlRoute
  '/plumbing': typeof PlumbingRoute
  '/roofing': typeof RoofingRoute
  '/water-damage': typeof WaterDamageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/floor-coating': typeof FloorCoatingRoute
  '/login': typeof LoginRoute
  '/pest-control': typeof PestControlRoute
  '/plumbing': typeof PlumbingRoute
  '/roofing': typeof RoofingRoute
  '/water-damage': typeof WaterDamageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/floor-coating'
    | '/login'
    | '/pest-control'
    | '/plumbing'
    | '/roofing'
    | '/water-damage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/floor-coating'
    | '/login'
    | '/pest-control'
    | '/plumbing'
    | '/roofing'
    | '/water-damage'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/floor-coating'
    | '/login'
    | '/pest-control'
    | '/plumbing'
    | '/roofing'
    | '/water-damage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  FloorCoatingRoute: typeof FloorCoatingRoute
  LoginRoute: typeof LoginRoute
  PestControlRoute: typeof PestControlRoute
  PlumbingRoute: typeof PlumbingRoute
  RoofingRoute: typeof RoofingRoute
  WaterDamageRoute: typeof WaterDamageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/water-damage': {
      id: '/water-damage'
      path: '/water-damage'
      fullPath: '/water-damage'
      preLoaderRoute: typeof WaterDamageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roofing': {
      id: '/roofing'
      path: '/roofing'
      fullPath: '/roofing'
      preLoaderRoute: typeof RoofingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plumbing': {
      id: '/plumbing'
      path: '/plumbing'
      fullPath: '/plumbing'
      preLoaderRoute: typeof PlumbingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pest-control': {
      id: '/pest-control'
      path: '/pest-control'
      fullPath: '/pest-control'
      preLoaderRoute: typeof PestControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floor-coating': {
      id: '/floor-coating'
      path: '/floor-coating'
      fullPath: '/floor-coating'
      preLoaderRoute: typeof FloorCoatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  FloorCoatingRoute: FloorCoatingRoute,
  LoginRoute: LoginRoute,
  PestControlRoute: PestControlRoute,
  PlumbingRoute: PlumbingRoute,
  RoofingRoute: RoofingRoute,
  WaterDamageRoute: WaterDamageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
